### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-sarayfg#1]
Super buen trabajo @sarayfg 

Algunas pistas para acabarlo:

- [x] En el terminal en el que se arranca la app con `npm start` aparecen dos warnings, apañalos.
- [x] Si utilizas SASS, recuerda instalarlo y grabarlo en el package.json con `--save`
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Nombra los archivos que contengan componentes con camelcase y mayúscula inicial, por ejemplo 'PokemonList.js'
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes.
- [x] Al componente de 'Pokemon' le estás pasando dos props, data con todo el array e item con el objeto que contiene los datos de un pokemon. ¿Crees que necesita los dos?
- [x] En PokemonList estás englobando el componente Pokemon en un li, y después dentro de Pokemon estás añadiendo otro li. Esto genera lis anidados y un HTML inválido.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Elimina el código comentado
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código

Si tienes cualquier duda, avisa!

Al turrón

**Comment by sarayfg** [comment]
Listo! :)

**Comment by nasivuela** [comment]
Super buen trabajo @sarayfg !

Todavía hecho en falta un `h1` y que los estilos esten junto a sus componentes. Dale una vuelta y cerramos issue.

Te dejo más pistas por si quieres continuar practicando:

- Añade una página de detalle por cada pokemon
- Añade la posibilidad de marcar favoritos siguiendo estos pasos:
1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Al turrón!

**Comment by sarayfg** [comment]
El h1 y los archivos scss a sus compenentes están listos. Dejo eso actualizado en master para cerrar el issue y comienzo los siguientes en otra rama.
Te aviso cuando estén

**Comment by nasivuela** [comment]
Excelente!

![](https://media.giphy.com/media/gKmwTEH4vyd2M/giphy.gif)
